tb insert command and new placeholders
RoinujNosde/TitansBattle pull request #112
Opened 2023-08-13 04:37 UTC by thiagogebrimm

feat: add /tb insert command
feat: add %titansbattle_groups_size%" and ,"%titansbattle_participants_size% placeholders

2023-08-14 20:06 UTC, RoinujNosde commented on src/main/java/me/roinujnosde/titansbattle/listeners/JoinGameListener.java
> +        }
Não gostei muito disso aqui

2023-08-14 20:07 UTC, RoinujNosde commented
Seria melhor separar os placeholders em outra PR.

2023-08-14 20:17 UTC, thiagogebrimm commented on src/main/java/me/roinujnosde/titansbattle/listeners/JoinGameListener.java
> +        }
Como poderia fazer, não pensei em outra maneira

2023-08-16 01:51 UTC, SrBedrock commented on src/main/java/me/roinujnosde/titansbattle/listeners/JoinGameListener.java
> +        }
Caso seja necessário anotações, é melhor em inglês.

2023-08-16 02:00 UTC, thiagogebrimm commented on src/main/java/me/roinujnosde/titansbattle/listeners/JoinGameListener.java
> +        }
Removi, eu que me esqueci, pensei que ele estava falando de outra coisa

2023-08-16 02:04 UTC, RoinujNosde commented on src/main/java/me/roinujnosde/titansbattle/listeners/JoinGameListener.java
> +        }
> pensei que ele estava falando de outra coisa

E estava. Poderia ter um método novo, tipo o onJoin(). Não pensei direito sobre isso.

2023-10-01 22:28 UTC, RoinujNosde requested changes
- Separe as mudanças em diferentes PRs.
- A solução usando o método estático `isInsertCalled` não é muito boa. Recomendo adicionar um novo método similar ao `onJoin()`, talvez `onLateJoin()`.

2023-10-06 00:06 UTC, thiagogebrimm commented
> * Separe as mudanças em diferentes PRs.
> * A solução usando o método estático `isInsertCalled` não é muito boa. Recomendo adicionar um novo método similar ao `onJoin()`, talvez `onLateJoin()`.

Essa PR agora é só as placeholders, vou refazer o insert depois

2023-10-13 22:03 UTC, RoinujNosde approved these changes

2023-10-13 22:04 UTC, merged