Correção de kits com novo formato NBT
RoinujNosde/TitansBattle pull request #128
Opened 2024-08-13 23:09 UTC by leogianfagna

Isso corrige o problema que nas novas versões não está sendo possível criar kits pois nenhum dado NBT era salvo no arquivo (encantamentos, atributos, etc). Isso ocorria por conta que a api do NBTTAG passou a usar a classe NBT e não NBTItems, tornando vários métodos **deprecated**.

2024-08-13 23:56 UTC, RoinujNosde requested changes

2024-08-13 23:56 UTC, RoinujNosde commented on src/main/java/me/roinujnosde/titansbattle/types/Kit.java
> +    });
```java
NBT.modify(item, nbtItem -> nbtItem.setBoolean(NBT_TAG, true));
```

2024-08-13 23:56 UTC, RoinujNosde commented on src/main/resources/plugin.yml
> +api-version: 1.21
```yml
api-version: 1.13
```

2024-08-14 00:34 UTC, leogianfagna reviewed
Review implementado nos novos commits.

2024-08-14 00:35 UTC, RoinujNosde approved these changes

2024-08-14 00:55 UTC, merged